<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Weekly Report - {{ $period }}</title>
    <style>
        @media print {
            body { margin: 0; }
            .no-print { display: none; }
        }
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 40px;
            border-bottom: 3px solid #667eea;
            padding-bottom: 20px;
        }
        .header h1 {
            color: #667eea;
            margin: 0;
            font-size: 28px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background: #667eea;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }
        td {
            padding: 10px 12px;
            border-bottom: 1px solid #e5e7eb;
        }
        tr:nth-child(even) {
            background: #f9fafb;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            color: #999;
            font-size: 12px;
            border-top: 1px solid #e5e7eb;
            padding-top: 20px;
        }
        .summary-box {
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        .summary-item {
            display: inline-block;
            width: 48%;
            margin-bottom: 10px;
        }
        .print-button {
            position: fixed;
            top: 20px;
            right: 20px;
            background: #667eea;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 8px;
            cursor: pointer;
            font-weight: 600;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        }
        .print-button:hover {
            background: #764ba2;
        }
    </style>
</head>
<body>
    <button onclick="window.print()" class="print-button no-print">
        Print / Save as PDF
    </button>
    <div class="header">
        <h1>Weekly Sales Report</h1>
        <p><strong>Period:</strong> {{ $period }}</p>
        <p><strong>Generated:</strong> {{ now()->format('F d, Y h:i A') }}</p>
        <p><strong>Generated by:</strong> {{ auth()->user()->name }}</p>
    </div>

    <div class="summary-box">
        <h2 style="margin-top: 0;">Summary</h2>
        <div class="summary-item">
            <div style="font-size: 14px; opacity: 0.9;">Total Sales</div>
            <div style="font-size: 24px; font-weight: bold;">₱{{ number_format($totalSales, 2) }}</div>
        </div>
        <div class="summary-item">
            <div style="font-size: 14px; opacity: 0.9;">Transactions</div>
            <div style="font-size: 24px; font-weight: bold;">{{ $transactionCount }}</div>
        </div>
    </div>

    @if($sales->count() > 0)
    <h3>Transaction Details</h3>
    <table>
        <thead>
            <tr>
                <th>Sale ID</th>
                <th>Date/Time</th>
                <th>Customer</th>
                <th>Items</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sales as $sale)
            <tr>
                <td>#{{ $sale->id }}</td>
                <td>{{ \Carbon\Carbon::parse($sale->sale_date)->format('Y-m-d H:i') }}</td>
                <td>{{ $sale->customer_name ?? 'Walk-in' }}</td>
                <td>{{ $sale->items->count() }}</td>
                <td>₱{{ number_format($sale->total_amount, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <div style="padding: 12px; background: #f9fafb; margin-bottom: 8px; border-left: 4px solid #667eea;">
        No transactions recorded for this period.
    </div>
    @endif

    <div class="footer">
        <p>Elenagin System - Automated Weekly Report</p>
        <p>This is a computer-generated document. No signature is required.</p>
    </div>
</body>
</html>
